[versions]
# libraries
junit = "4.13.2"
junit5 = "5.10.2"
kodein = "7.20.2"
opentest4j = "1.3.0"
mavenModel = "3.9.9"
kotlinx-serialization = "1.6.3"
jsoup = "1.18.3"

# plugins
changelog = "2.4.0"
intelliJPlatform = "2.10.4"
kotlin = "2.2.0"
kover = "0.9.1"
qodana = "2025.1.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit5 = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }
junit5-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "1.10.2" }
kodein = { group = "org.kodein.di", name = "kodein-di-jvm", version.ref = "kodein" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
mavenModel = { group = "org.apache.maven", name = "maven-model", version.ref = "mavenModel" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
